"""Regex parser module."""

from recheck.parser.ast import (
    Node,
    Pattern,
    Disjunction,
    Sequence,
    Capture,
    NamedCapture,
    NonCapture,
    Repeat,
    Star,
    Plus,
    Question,
    Quantifier,
    Char,
    Dot,
    CharClass,
    CharClassRange,
    Backref,
    NamedBackref,
    LookAhead,
    NegLookAhead,
    LookBehind,
    NegLookBehind,
    WordBoundary,
    NonWordBoundary,
    LineStart,
    LineEnd,
    StringStart,
    StringEnd,
)
from recheck.parser.parser import parse
from recheck.parser.flags import Flags

__all__ = [
    "Node",
    "Pattern",
    "Disjunction",
    "Sequence",
    "Capture",
    "NamedCapture",
    "NonCapture",
    "Repeat",
    "Star",
    "Plus",
    "Question",
    "Quantifier",
    "Char",
    "Dot",
    "CharClass",
    "CharClassRange",
    "Backref",
    "NamedBackref",
    "LookAhead",
    "NegLookAhead",
    "LookBehind",
    "NegLookBehind",
    "WordBoundary",
    "NonWordBoundary",
    "LineStart",
    "LineEnd",
    "StringStart",
    "StringEnd",
    "parse",
    "Flags",
]
